import React, { Component } from 'react';
import {Link} from "react-router";
import {withRouter} from 'react-router';
import { hashHistory } from 'react-router';
import injectTapEventPlugin from 'react-tap-event-plugin';
import RaisedButton from 'material-ui/RaisedButton';

var Welcome = React.createClass({

    render(){
        return (
            <div>
                <div className="backgroundImage">
                    <div className="welcome-text">
                        <h1> Welcome to R.Codes</h1>
                        <br/>
                        <p> Discover the newest code snippets of the R universe </p>
                        <br/>
                         <Link to="/Market" className="">
                            <RaisedButton label="Explore" style={{}} />
                        </Link>
                    </div>

                    <div className="welcomeBoard">
                        <div className="welcome-info-header" style={{padding: 2}}>
                            <h4>it's about creating value </h4>
                        </div>
                        <div className='welcome-info'>
                            <p>  In the R world,
                              value is generated by realizing meaningfull data science projects.
                              Thanks to the numerous open source packages, R projects start from a solid foundation.
                              We from R.Codes take it one step further and offer worked out script solutions build by
                              experts from multiple areas.<br/>
                            </p>
                            <p> The R universe is not isolated - with the Shiny&reg; package, R solutions can easily be
                              ported to the web. To convert standart Shiny's standart layout to a professional, it takes
                              HTML5/CSS3 & JavaScript experience. While learning those languages and frameworks takes
                              time, project templates offer the same user experience at a minimum of efford.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        )
    }

});

module.exports = Welcome;
